controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_producto_search:
    path: /buscar
    controller: App\Controller\ProductoController::search

